package com.umoove.all;

import android.graphics.PointF;

/* compiled from: UMEyeData */
public class e {
    public int a;
    public int b;
    public PointF eJk = new PointF();
    public PointF eJl = new PointF();
    public PointF eJm = new PointF();
    public PointF eJn = new PointF();
    public PointF eJo = new PointF();
    public PointF eJp = new PointF();
    public PointF eJq = new PointF();
    public long eJr = -1;
    public float g;
    public int j;
    public int l;
    public float m;
    public float n;

    public String toString() {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("");
        stringBuilder.append("EstimatedPosition L [");
        stringBuilder.append(this.eJm.x);
        String str = ",";
        stringBuilder.append(str);
        stringBuilder.append(this.eJm.y);
        String str2 = "], R [";
        stringBuilder.append(str2);
        stringBuilder.append(this.eJn.x);
        stringBuilder.append(str);
        stringBuilder.append(this.eJn.y);
        String str3 = "] \r\n";
        stringBuilder.append(str3);
        String stringBuilder2 = stringBuilder.toString();
        StringBuilder stringBuilder3 = new StringBuilder();
        stringBuilder3.append(stringBuilder2);
        stringBuilder3.append("Position Reliability L ");
        stringBuilder3.append(this.a);
        stringBuilder3.append(", R ");
        stringBuilder3.append(this.b);
        stringBuilder3.append("\r\n");
        stringBuilder2 = stringBuilder3.toString();
        stringBuilder3 = new StringBuilder();
        stringBuilder3.append(stringBuilder2);
        stringBuilder3.append("IrisMovement L [");
        stringBuilder3.append(this.eJo.x);
        stringBuilder3.append(str);
        stringBuilder3.append(this.eJo.y);
        stringBuilder3.append(str2);
        stringBuilder3.append(this.eJp.x);
        stringBuilder3.append(str);
        stringBuilder3.append(this.eJp.y);
        stringBuilder3.append("]\r\n");
        stringBuilder2 = stringBuilder3.toString();
        stringBuilder3 = new StringBuilder();
        stringBuilder3.append(stringBuilder2);
        stringBuilder3.append("Movement Reliability L [");
        stringBuilder3.append(this.eJk.x);
        stringBuilder3.append(str);
        stringBuilder3.append(this.eJk.y);
        stringBuilder3.append(str2);
        stringBuilder3.append(this.eJl.x);
        stringBuilder3.append(str);
        stringBuilder3.append(this.eJl.y);
        stringBuilder3.append(str3);
        stringBuilder2 = stringBuilder3.toString();
        StringBuilder stringBuilder4 = new StringBuilder();
        stringBuilder4.append(stringBuilder2);
        stringBuilder4.append("Eye Line Angle: ");
        stringBuilder4.append(this.g);
        stringBuilder2 = " \r\n";
        stringBuilder4.append(stringBuilder2);
        str = stringBuilder4.toString();
        StringBuilder stringBuilder5 = new StringBuilder();
        stringBuilder5.append(str);
        stringBuilder5.append("Eye Movement Type: ");
        stringBuilder5.append(this.j);
        stringBuilder5.append(stringBuilder2);
        str = stringBuilder5.toString();
        stringBuilder5 = new StringBuilder();
        stringBuilder5.append(str);
        stringBuilder5.append("Eye Movement Vector [");
        stringBuilder5.append(this.eJq.x);
        stringBuilder5.append(" , ");
        stringBuilder5.append(this.eJq.y);
        stringBuilder5.append(str3);
        str = stringBuilder5.toString();
        stringBuilder5 = new StringBuilder();
        stringBuilder5.append(str);
        stringBuilder5.append("Iris radius: ");
        stringBuilder5.append(this.l);
        stringBuilder5.append(stringBuilder2);
        str = stringBuilder5.toString();
        stringBuilder5 = new StringBuilder();
        stringBuilder5.append(str);
        stringBuilder5.append("oevrallQuality Left: ");
        stringBuilder5.append(this.m);
        stringBuilder5.append(" Right: ");
        stringBuilder5.append(this.n);
        stringBuilder5.append(stringBuilder2);
        return stringBuilder5.toString();
    }
}
